site_name: 'CITZ IMB SSO Express (NPM Package)'
site_description: "An npm package that offers an integration solution for connecting Express applications requiring authentication to the B.C. government's Single Sign-On service."
docs_dir: 'techdocs/docs'
repo_url: 'https://github.com/bcgov/citz-imb-sso-express'
edit_uri: edit/main/techdocs/docs
nav:
  - Introduction: index.md
  - Getting Started:
      - Installing the Package: getting-started/installing-the-package.md
      - Quick Start Guide: getting-started/quick-start-guide.md
      - Environment Variables: getting-started/environment-variables.md
      - SSO Integration Settings: getting-started/integration-settings.md
  - Using The Package:
      - Protecting a Route: using-the-package/protecting-a-route.md
      - Getting User Information: using-the-package/getting-user-information.md
      - Initialization Options: using-the-package/init-options.md
      - APIs & Components:
          - sso: using-the-package/apis-&-components/sso.md
          - protectedRoute: using-the-package/apis-&-components/protected-route.md
          - req.user: using-the-package/apis-&-components/req-user.md
          - hasRoles: using-the-package/apis-&-components/has-roles.md
      - Module Exports: using-the-package/module-exports.md
      - TypeScript Types: using-the-package/typescript-types.md
      - Troubleshooting: using-the-package/troubleshooting.md
  - Authentication Flow: authentication-flow.md
  - Purpose and Benefits: purpose-and-benefits.md
