site_name: "CITZ IMB SSO Express (NPM Package)"
site_description: "An npm package that offers an integration solution for connecting Express applications requiring authentication to the B.C. government's Single Sign-On service."
docs_dir: "docs"
repo_url: "https://github.com/bcgov/citz-imb-sso-express"
edit_uri: edit/main/docs
nav:
    - Introduction: index.md
    - Getting started: getting-started.md
    - Configuration: configuration.md
    - Tips and tricks: tips-and-tricks.md
    - About us: about-us.md
plugins:
    - techdocs-core
    - git-revision-date-localized
markdown_extensions:
    - md_in_html
