name: Build TechDocs with DevHub TechDocs Publish Action

on:
    workflow_dispatch:
    release:
        types: [released]
    push:
        branches: [ main ]
        paths:
            - "mkdocs.yml"
            - "techdocs/docs/**"
            - "catalog-info.yaml"
    pull_request:
        branches: [ main ]
        paths:
            - "mkdocs.yml"
            - "techdocs/docs/**"
            - "catalog-info.yaml"

jobs:
    test_techdocs_build_job:
        runs-on: ubuntu-latest

        name: A job to build and publish techdocs content
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: '0'
            -   name: Build TechDocs
                uses: bcgov/devhub-techdocs-publish@stable
                id: build_and_publish
                with:
                    publish: 'true' 
                    production:  ${{ github.event_name == 'release' }} # will need to be tested. Only publish to prod on release
                    bucket_name: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
                    s3_access_key_id: ${{ secrets.TECHDOCS_AWS_ACCESS_KEY_ID }}
                    s3_secret_access_key: ${{ secrets.TECHDOCS_AWS_SECRET_ACCESS_KEY }}
                    s3_region: ${{ secrets.TECHDOCS_AWS_REGION }}
                    s3_endpoint: ${{ secrets.TECHDOCS_AWS_ENDPOINT }}

